mp:
  messaging:
    incoming:
      'audit-events':
        topic: "k8s-achievements.ingestion.audit-events.json"
      'kubernetes-events':
        topic: "k8s-achievements.ingestion.kubernetes-events.json"
