kafka:
  bootstrap:
    servers: kafka-bootstrap.rh-sandbox.irori.se
mp:
  messaging:
    connector:
      smallrye-kafka:
        security:
          #protocol: SSL
        ssl:
          truststore:
            #location: something.jks
            #password: xyz
    incoming:
      'audit-events':
        connector: smallrye-kafka
        topic: "k8s-achievements.ingestion.audit-events.json"
        value:
          deserializer: se.irori.kafka.AuditEventDeserializer
      'kubernetes-events':
        connector: smallrye-kafka
        topic: "k8s-achievements.ingestion.kubernetes-events.json"
        value:
          deserializer: se.irori.kafka.AuditEventDeserializer
    outgoing:
      'subject-actions':
        connector: smallrye-kafka
        topic: "k8s-achievements.processing.subject-actions.json"
